name: Algoteque UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    env:
      BROWSER: ${{ matrix.browser }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Playwright browsers
        run: playwright install

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Parallel tests (${{ matrix.browser }})
        run: dotnet test --no-build --configuration Release --filter "TestCategory!=Skip"
